spring:
  application:
    name: pay-as-you-learn
  datasource:
    url: jdbc:postgresql://localhost:5432/pay_as_you_learn
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

server:
  port: 8080
